#!/bin/sh

system=`uname -s`
nseed_byuser=111111
echo ${nseed_byuser} > nseed_runtime

# rm -f *.o
make
cp input.ampt ana/
echo "#  AMPT started at " `date` > start.time
./ampt < nseed_runtime > nohup.out
uname -n >> nohup.out
cat start.time >> nohup.out
rm -f start.time
echo "#  AMPT Program finished at " `date` >> nohup.out
echo "#  AMPT Program finished at " `date` 



